### ISSUE TITLE
I don't know other method to communicate with you so...

### ISSUE THREAD

**Issue by MaquedaPaul** [Raymai97/SuperCMD#3]
Hi! since i don't know how to email you or DM through github, i'm forced to talk with you through this issue not nearly related to the thing i want to talk, here it goes:
I don't know how, when or what exactly is QuickAdmin by MaiSoft, i've searched that on Google and it let me found you. So, that is the main question, i suppose you don't want to talk about it in this issue and you want other canal so here is my email: maquedapablodavid@gmail.com.
By the way, that program is installed and detected as a virus by Norton Eraser that's why i'm worried.

**Comment by Raymai97** [comment]
Hi @MaquedaPaul 

Good day. I will reply you here so that anyone with the same question in future would have the answer.

First of all, rest assured it's not a virus. QuickAdmin was a program I created to mitigate the annoyance of UAC. I was using a very shitty netbook at the time, and this program helped me tremendously in tackling these issues:

* When I right-click EXE and choose "Run as Administrator", the UAC would check the EXE whether it has a valid digital signature, before showing the famous UAC prompt.
* If the EXE has valid digital signature, it would show green/blue UAC prompt. Otherwise, it will show yellow/orange UAC prompt. Yes, UAC checks EXE for this, and you can't disable it.
* So if your PC is slow, and the EXE is big, you may have to wait more than a few seconds before the UAC prompt shows up! Also, I have already explicitly select "Run as Administrator", why does the UAC ask me again?
* QuickAdmin allows you to bypass this crap. When you choose "Run as QuickAdmin", the QA would just run the program as administrator, no question would be asked.
* Sometimes there might be certain programs that you use often, and they require run as administrator. In this case, QuickAdmin also support Elevated Shortcut, where you can run your favorite program shortcuts as administrator without facing the UAC prompt.

Now, the reason why I stop distributing QuickAdmin is because this stuff was designed with speed and perfect functionality in mind. It's not designed to withstand any kind of "security exploit". If some hackers decided that QA is popular and tried to exploit it, then it would become a security backdoor. Also, nowadays PC are much faster, the slow EXE execution is no longer that painful compared to my shitty netbook I have to use back then. :)

**Comment by MaquedaPaul** [comment]
I appreciate your reply! Thanks! Now i understand better what it is. 
I'll close this issue with this comment and also take the opportunity to tell you that maybe SmartGenius used your program for their keyboard app, i say this because when i opened that program it showed an error related to QA and helper.vbs.
Thanks again and wish you all the best!
